import React from 'react';
export const analyticsDetails = () => <div>analytics distinct</div>;
export const analytics_detail_0 = (p:any)=> <div>analytics 0 KPI</div>;
export const analytics_detail_1 = (p:any)=> <div>analytics 1 trend</div>;
export const analytics_detail_2 = (p:any)=> <div>analytics 2 SLA breach</div>;
export const analytics_detail_3 = (p:any)=> <div>analytics 3 satisfaction</div>;
export const analytics_detail_4 = (p:any)=> <div>analytics 4 KPI</div>;
export const analytics_detail_5 = (p:any)=> <div>analytics 5 trend</div>;
export const analytics_detail_6 = (p:any)=> <div>analytics 6 SLA breach</div>;
export const analytics_detail_7 = (p:any)=> <div>analytics 7 satisfaction</div>;
export const analytics_detail_8 = (p:any)=> <div>analytics 8 KPI</div>;
export const analytics_detail_9 = (p:any)=> <div>analytics 9 trend</div>;
export const analytics_detail_10 = (p:any)=> <div>analytics 10 SLA breach</div>;
export const analytics_detail_11 = (p:any)=> <div>analytics 11 satisfaction</div>;
export const analytics_detail_12 = (p:any)=> <div>analytics 12 KPI</div>;
export const analytics_detail_13 = (p:any)=> <div>analytics 13 trend</div>;
export const analytics_detail_14 = (p:any)=> <div>analytics 14 SLA breach</div>;
export const analytics_detail_15 = (p:any)=> <div>analytics 15 satisfaction</div>;
export const analytics_detail_16 = (p:any)=> <div>analytics 16 KPI</div>;
export const analytics_detail_17 = (p:any)=> <div>analytics 17 trend</div>;
export const analytics_detail_18 = (p:any)=> <div>analytics 18 SLA breach</div>;
export const analytics_detail_19 = (p:any)=> <div>analytics 19 satisfaction</div>;