import React from 'react';
export const escalationDetails = () => <div>escalation distinct</div>;
export const escalation_detail_0 = (p:any)=> <div>escalation 0 auto-escalate</div>;
export const escalation_detail_1 = (p:any)=> <div>escalation 1 SLA breach</div>;
export const escalation_detail_2 = (p:any)=> <div>escalation 2 commissioner</div>;
export const escalation_detail_3 = (p:any)=> <div>escalation 3 auto-escalate</div>;
export const escalation_detail_4 = (p:any)=> <div>escalation 4 SLA breach</div>;
export const escalation_detail_5 = (p:any)=> <div>escalation 5 commissioner</div>;
export const escalation_detail_6 = (p:any)=> <div>escalation 6 auto-escalate</div>;
export const escalation_detail_7 = (p:any)=> <div>escalation 7 SLA breach</div>;
export const escalation_detail_8 = (p:any)=> <div>escalation 8 commissioner</div>;
export const escalation_detail_9 = (p:any)=> <div>escalation 9 auto-escalate</div>;
export const escalation_detail_10 = (p:any)=> <div>escalation 10 SLA breach</div>;
export const escalation_detail_11 = (p:any)=> <div>escalation 11 commissioner</div>;
export const escalation_detail_12 = (p:any)=> <div>escalation 12 auto-escalate</div>;
export const escalation_detail_13 = (p:any)=> <div>escalation 13 SLA breach</div>;
export const escalation_detail_14 = (p:any)=> <div>escalation 14 commissioner</div>;
export const escalation_detail_15 = (p:any)=> <div>escalation 15 auto-escalate</div>;
export const escalation_detail_16 = (p:any)=> <div>escalation 16 SLA breach</div>;
export const escalation_detail_17 = (p:any)=> <div>escalation 17 commissioner</div>;
export const escalation_detail_18 = (p:any)=> <div>escalation 18 auto-escalate</div>;
export const escalation_detail_19 = (p:any)=> <div>escalation 19 SLA breach</div>;