import React from 'react';
export const resolutionDetails = () => <div>resolution distinct</div>;
export const resolution_detail_0 = (p:any)=> <div>resolution 0 workflow</div>;
export const resolution_detail_1 = (p:any)=> <div>resolution 1 SLA 48h</div>;
export const resolution_detail_2 = (p:any)=> <div>resolution 2 closure</div>;
export const resolution_detail_3 = (p:any)=> <div>resolution 3 verification</div>;
export const resolution_detail_4 = (p:any)=> <div>resolution 4 workflow</div>;
export const resolution_detail_5 = (p:any)=> <div>resolution 5 SLA 48h</div>;
export const resolution_detail_6 = (p:any)=> <div>resolution 6 closure</div>;
export const resolution_detail_7 = (p:any)=> <div>resolution 7 verification</div>;
export const resolution_detail_8 = (p:any)=> <div>resolution 8 workflow</div>;
export const resolution_detail_9 = (p:any)=> <div>resolution 9 SLA 48h</div>;
export const resolution_detail_10 = (p:any)=> <div>resolution 10 closure</div>;
export const resolution_detail_11 = (p:any)=> <div>resolution 11 verification</div>;
export const resolution_detail_12 = (p:any)=> <div>resolution 12 workflow</div>;
export const resolution_detail_13 = (p:any)=> <div>resolution 13 SLA 48h</div>;
export const resolution_detail_14 = (p:any)=> <div>resolution 14 closure</div>;
export const resolution_detail_15 = (p:any)=> <div>resolution 15 verification</div>;
export const resolution_detail_16 = (p:any)=> <div>resolution 16 workflow</div>;
export const resolution_detail_17 = (p:any)=> <div>resolution 17 SLA 48h</div>;
export const resolution_detail_18 = (p:any)=> <div>resolution 18 closure</div>;
export const resolution_detail_19 = (p:any)=> <div>resolution 19 verification</div>;